# Generated by Django 3.1.5 on 2022-03-09 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0007_auto_20220226_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('days', models.PositiveIntegerField()),
                ('hours', models.FloatField()),
                ('pay', models.PositiveIntegerField()),
                ('slow', models.PositiveIntegerField()),
                ('busy', models.PositiveIntegerField()),
                ('envo', models.CharField(max_length=200)),
                ('mngmt', models.CharField(max_length=200)),
                ('balance', models.CharField(max_length=200)),
                ('comments', models.CharField(max_length=500)),
                ('rating', models.PositiveIntegerField()),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
