# Generated by Django 3.1.5 on 2022-03-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0008_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='balance',
        ),
        migrations.AlterField(
            model_name='review',
            name='envo',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='mngmt',
            field=models.PositiveIntegerField(),
        ),
    ]
