# Generated by Django 3.1.5 on 2022-03-15 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0008_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
