# Generated by Django 3.1.5 on 2022-03-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0009_auto_20220315_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='envo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='review',
            name='mngmt',
            field=models.CharField(max_length=200),
        ),
    ]
