# Generated by Django 3.1.5 on 2022-03-30 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0010_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='location',
        ),
    ]
