# Generated by Django 3.1.5 on 2022-04-02 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0011_remove_info_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='address',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='review',
            name='zip',
            field=models.PositiveIntegerField(default=None, validators=[django.core.validators.MaxValueValidator(99950)]),
        ),
    ]
